export type PreferenceKey =
  | "rated"
  | "ratedThreshold"
  | "originals"
  | "cookies"
  | "preloadVideos"
  | "tagSuggestionsCount"
  | "resultsLayout"
  | "pageSize"
  | "showMetadata"
  | "showComments"
  | "sort"
  | "themeId"
  | "autoPlay"
  | "hideSeen"
  | "autoscrollDelay"
  | "showPostDetails"
  | "backends";
